Update compare_syns.py
Added writestats() and title to plots. Currently writestats() (lines 141-144) is commented out because of bug. With writestats implemented the following error occurs:

Traceback (most recent call last):
  File "compare_syns.py", line 226, in writestats
    resi = "{0:.2f}".format(np.sum(tr.data*syn[0].data[:-1])/np.sum(np.square(syn[0].data[:-1])))
ValueError: operands could not be broadcast together with shapes (38,) (5425,) 

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "compare_syns.py", line 142, in main
    writestats(statfile, st, chan)
  File "compare_syns.py", line 238, in writestats
    if debug:
NameError: name 'debug' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "compare_syns.py", line 245, in <module>
    main()
  File "compare_syns.py", line 144, in main
    print('Problem with: ' + sta)
UnboundLocalError: local variable 'sta' referenced before assignment